# Generated by Django 4.2.26 on 2025-12-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="can_create_namespace",
        ),
        migrations.AddField(
            model_name="user",
            name="can_create_contributor",
            field=models.BooleanField(
                default=True, verbose_name="can create contributor"
            ),
        ),
    ]
