# Generated by Django 4.2.26 on 2025-12-01 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.SlugField(
                        help_text="Unique contributor identifier (lowercase, alphanumeric, hyphens)",
                        max_length=100,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=200, verbose_name="display name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("avatar_url", models.URLField(blank=True, verbose_name="avatar URL")),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="company"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "policy_count",
                    models.IntegerField(default=0, verbose_name="policy count"),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="download count"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_personal",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a personal contributor for a single user",
                        verbose_name="personal contributor",
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        related_name="owned_contributors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owners",
                    ),
                ),
            ],
            options={
                "verbose_name": "contributor",
                "verbose_name_plural": "contributors",
                "db_table": "contributors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContributorLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="contributors.contributor",
                    ),
                ),
            ],
            options={
                "verbose_name": "contributor link",
                "verbose_name_plural": "contributor links",
                "db_table": "contributor_links",
                "ordering": ["name"],
            },
        ),
    ]
