# Generated by Django 4.2.26 on 2025-12-01 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contributors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.SlugField(
                        help_text="Policy name (lowercase, alphanumeric, hyphens)",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=200, verbose_name="display name"),
                ),
                ("description", models.TextField(verbose_name="description")),
                ("repository_url", models.URLField(verbose_name="repository URL")),
                (
                    "repository_branch",
                    models.CharField(
                        default="main", max_length=100, verbose_name="repository branch"
                    ),
                ),
                ("readme", models.TextField(blank=True, verbose_name="README")),
                (
                    "documentation_url",
                    models.URLField(blank=True, verbose_name="documentation URL"),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="license"
                    ),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="download count"),
                ),
                (
                    "star_count",
                    models.IntegerField(default=0, verbose_name="star count"),
                ),
                (
                    "is_deprecated",
                    models.BooleanField(default=False, verbose_name="deprecated"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="contributors.contributor",
                    ),
                ),
            ],
            options={
                "verbose_name": "policy",
                "verbose_name_plural": "policies",
                "db_table": "policies",
                "ordering": ["-download_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.SlugField(unique=True, verbose_name="name")),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PolicyVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.CharField(
                        help_text="Semantic version (e.g., 1.0.0)",
                        max_length=50,
                        verbose_name="version",
                    ),
                ),
                (
                    "git_commit",
                    models.CharField(max_length=40, verbose_name="git commit SHA"),
                ),
                (
                    "git_tag",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="git tag"
                    ),
                ),
                ("changelog", models.TextField(blank=True, verbose_name="changelog")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                (
                    "archive_url",
                    models.URLField(blank=True, verbose_name="archive URL"),
                ),
                (
                    "archive_size",
                    models.IntegerField(default=0, verbose_name="archive size (bytes)"),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="SHA256 checksum"
                    ),
                ),
                (
                    "dependencies",
                    models.JSONField(
                        blank=True, default=list, verbose_name="dependencies"
                    ),
                ),
                (
                    "selinux_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="SELinux version"
                    ),
                ),
                (
                    "supported_systems",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='e.g., ["RHEL 8", "RHEL 9", "Fedora 38"]',
                        verbose_name="supported systems",
                    ),
                ),
                (
                    "is_latest",
                    models.BooleanField(default=False, verbose_name="is latest"),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="download count"),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "verbose_name": "policy version",
                "verbose_name_plural": "policy versions",
                "db_table": "policy_versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="file path"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("te", "Type Enforcement (.te)"),
                            ("fc", "File Contexts (.fc)"),
                            ("if", "Interface (.if)"),
                            ("pp", "Policy Package (.pp)"),
                            ("cil", "Common Intermediate Language (.cil)"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                        verbose_name="file type",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="content")),
                ("size", models.IntegerField(default=0, verbose_name="size (bytes)")),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="policies.policyversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "policy file",
                "verbose_name_plural": "policy files",
                "db_table": "policy_files",
                "ordering": ["file_path"],
            },
        ),
        migrations.AddField(
            model_name="policy",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="policies", to="policies.tag"
            ),
        ),
        migrations.CreateModel(
            name="DownloadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP address")),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="policies.policy",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="policies.policyversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "download log",
                "verbose_name_plural": "download logs",
                "db_table": "download_logs",
            },
        ),
        migrations.AddIndex(
            model_name="policyversion",
            index=models.Index(
                fields=["policy", "version"], name="policy_vers_policy__21474d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policyversion",
            index=models.Index(
                fields=["is_latest"], name="policy_vers_is_late_01fea7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="policyversion",
            unique_together={("policy", "version")},
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["contributor", "name"], name="policies_contrib_49a22b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["is_deprecated", "is_active"],
                name="policies_is_depr_ea7dc6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="policy",
            unique_together={("contributor", "name")},
        ),
        migrations.AddIndex(
            model_name="downloadlog",
            index=models.Index(
                fields=["policy", "created_at"], name="download_lo_policy__de3bdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="downloadlog",
            index=models.Index(
                fields=["version", "created_at"], name="download_lo_version_848aee_idx"
            ),
        ),
    ]
