# Generated by Django 4.2.26 on 2025-12-01 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "score",
                    models.SmallIntegerField(
                        choices=[
                            (1, "1 stars"),
                            (2, "2 stars"),
                            (3, "3 stars"),
                            (4, "4 stars"),
                            (5, "5 stars"),
                        ],
                        help_text="Rating from 1 to 5 stars",
                        verbose_name="rating score",
                    ),
                ),
                ("review", models.TextField(blank=True, verbose_name="review")),
                (
                    "helpful_count",
                    models.IntegerField(default=0, verbose_name="helpful count"),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="policies.policy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "rating",
                "verbose_name_plural": "ratings",
                "db_table": "ratings",
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.SmallIntegerField(
                        choices=[(1, "Upvote"), (-1, "Downvote")],
                        help_text="1 for upvote, -1 for downvote",
                        verbose_name="vote value",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="comment")),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="policies.policy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "vote",
                "verbose_name_plural": "votes",
                "db_table": "votes",
                "indexes": [
                    models.Index(
                        fields=["policy", "value"], name="votes_policy__c97cdb_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="votes_user_id_a33ac6_idx"
                    ),
                ],
                "unique_together": {("user", "policy")},
            },
        ),
        migrations.CreateModel(
            name="RatingHelpfulness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_helpful",
                    models.BooleanField(default=True, verbose_name="is helpful"),
                ),
                (
                    "rating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helpfulness",
                        to="voting.rating",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_helpfulness",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "rating helpfulness",
                "verbose_name_plural": "rating helpfulness",
                "db_table": "rating_helpfulness",
                "unique_together": {("user", "rating")},
            },
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["policy", "score"], name="ratings_policy__a26d0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["user", "created_at"], name="ratings_user_id_7f9f81_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("user", "policy")},
        ),
    ]
